# Generated by Django 4.2.13 on 2024-09-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esperanza', '0002_alter_produit_couleur_alter_produit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
